### ISSUE TITLE
Closed_Text not used in Business Hours widget

### ISSUE THREAD

**Issue by FallenKN** [UranusWP/zeus-elementor#3]
Changing the closed text in the business hours widget has no effect since closed_text is defined but unused and won't display as a result.

https://github.com/UranusWP/zeus-elementor/blob/a1d4711281599fb5f4c34992ea034493bddd7d40/modules/business-hours/widgets/business-hours.php#L932

**Comment by UranusWP** [comment]
Hello, thanks for pointing this out, we will check this and fix it for the next release 👌

**Comment by UranusWP** [comment]
Hello, issue fixed on the next release 👍
